__version__ = '0.9.7.1'
__author__ = 'Giovanni Cannata'
__email__ = 'cannatag@gmail.com'
__license__ = 'LGPL v3'
__description__ = 'A strictly RFC 4511 conforming LDAP V3 pure Python client. Same codebase for Python 2 and Python 3'
__url__ = 'https://github.com/cannatag/pureLDAP'
__status__ = 'development'
